(function(){
"use strict";
var measurementId="G-BXCSZN56NT";
var consentKey="fpb-analytics-consent";
function consent(){try{return localStorage.getItem(consentKey)}catch(e){return null}}
function sendLeadIfReady(){if(location.pathname.endsWith("/thanks.html")&&sessionStorage.getItem("fpb-pending-lead")==="1"){window.gtag("event","generate_lead",{method:"website enquiry"});sessionStorage.removeItem("fpb-pending-lead")}}
function loadAnalytics(){if(window.fpbAnalyticsLoaded)return;window.fpbAnalyticsLoaded=true;window.dataLayer=window.dataLayer||[];window.gtag=window.gtag||function(){window.dataLayer.push(arguments)};window.gtag("js",new Date());window.gtag("config",measurementId);var script=document.createElement("script");script.async=true;script.src="https://www.googletagmanager.com/gtag/js?id="+encodeURIComponent(measurementId);document.head.appendChild(script);sendLeadIfReady()}
function showBanner(){var banner=document.getElementById("fpb-analytics-banner");if(!banner){banner=document.createElement("section");banner.id="fpb-analytics-banner";banner.setAttribute("role","region");banner.setAttribute("aria-label","Analytics choice");banner.style.cssText="position:fixed;z-index:9999;left:auto;right:16px;bottom:16px;width:min(360px,calc(100vw - 32px));max-width:360px;margin:0;padding:16px 18px;background:#16233b;color:#fff;border:1px solid #7086a4;border-radius:12px;box-shadow:0 8px 30px #0004;font:14px/1.5 system-ui,sans-serif";banner.innerHTML="<p style='margin:0 0 10px'>May we use Google Analytics to measure visits and improve this site? Your enquiry details and planner inputs are not sent to Google. <a href='/privacy.html' style='color:#ffd1a9'>Privacy notice</a></p><button type='button' data-fpb-allow style='margin-right:8px;padding:8px 12px'>Allow analytics</button><button type='button' data-fpb-reject style='padding:8px 12px'>Reject</button>";document.body.appendChild(banner);banner.querySelector("[data-fpb-allow]").addEventListener("click",function(){try{localStorage.setItem(consentKey,"accepted")}catch(e){}banner.remove();loadAnalytics()});banner.querySelector("[data-fpb-reject]").addEventListener("click",function(){try{localStorage.setItem(consentKey,"rejected")}catch(e){}banner.remove()})}banner.hidden=false}
function openSettings(){try{localStorage.removeItem(consentKey)}catch(e){}showBanner()}
var choice=consent();if(choice==="accepted")loadAnalytics();else if(choice!=="rejected")showBanner();
document.querySelectorAll("form[data-netlify]").forEach(function(form){form.addEventListener("submit",function(){try{sessionStorage.setItem("fpb-pending-lead","1")}catch(e){}})});
document.querySelectorAll("[data-open-analytics-settings]").forEach(function(button){button.addEventListener("click",openSettings)});
})();
